# Site settings
title: lambda
header-img: img/home.jpg
email: baoxianp@uci.edu
description: "Baoxiang Pan"
# baseurl: "/"
url: "http://lambdamore.github.io/"
#zhihu_username: pan-xiao-25
github_username: lambdamore
#facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
