# Site settings
title: PANaMA
header-img: img/HOMEPAGE.jpg
email: baoxianp@uci.edu
description: "Baoxiang Pan"
# baseurl: "/"
url: "http://panama2017.github.io/"
#zhihu_username: pan-xiao-25
github_username: panama2017
#facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
